[package]
name = "raydium-contract-instructions"
version = "0.1.0"
edition = "2021"


[dependencies]
solana-program = "1.9.4"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
arrayref = "0.3.6"
safe-transmute = "0.11.2"
bytemuck = "1.7.3"
borsh = "0.9.1"

[dev-dependencies]
solana-sdk = "1.9.4"
solana-client = "1.9.4"
